### ISSUE TITLE
This Is Amazing, Probably

### ISSUE THREAD

**Issue by bosscode21** [adamisntdead/QuantumComputing#3]
I'm sorry but when I try to run this code, an error comes up saying, " Traceback (most recent call last):
  File "C:/Users/Omid/Desktop/shortcuts/Coding/Python Codes/Quantum Register By QuSimPy.py", line 1, in <module>
    from QuSim import QuantumRegister
ModuleNotFoundError: No module named 'QuSim' "
However, going over the rest of the code, this is amazing! Great job!

**Comment by adamisntdead** [comment]
Thanks for the feedback, what version of python are you on?

**Comment by adamisntdead** [comment]
Okay, I added Travis and all builds are okay, It could be a windows issue, would you mind giving your OS version?

**Comment by bosscode21** [comment]
I use Python 3 on Windows 10.

**Comment by adamisntdead** [comment]
I haven't been able to reproduce this...

**Comment by bosscode21** [comment]
Its OK, I don't mind! Thanks for trying though!

**Comment by adamisntdead** [comment]
Do you have python 2.7 installed? If so, can you try this again

**Comment by bosscode21** [comment]
I'll try it!

**Comment by bosscode21** [comment]
It works! Like I said, it's amazing! Thanks! Great job!

**Comment by adamisntdead** [comment]
Good to hear! It passes the CI tests, so I would say there is an issue with your python setup. Thanks for supporting the project, and if you have any suggestions just say!
